tasks:
  - init: npm install
    command: >
      npm install -g @angular/cli &&
      ng analytics off &&
      npm start

github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addComment: true
    addBadge: false
    addLabel: prebuilt-in-gitpod
