tasks:
  - init: npm install
    command: >
      npm install -g @angular/cli &&
      npm start

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addComment: true
    addBadge: false
    addLabel: prebuilt-in-gitpod
