tasks:
  - init: npm install
    command: >
      npm install -g @angular/cli &&
      ng analytics off
  - command: gp await-port 4200 && gp preview $(gp url 4200)

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addComment: true
    addBadge: false
    addLabel: prebuilt-in-gitpod
