tasks:
  - init: gp env NG_CLI_ANALYTICS=ci && npm install -g @angular/cli && npm install
    command: npm start
  - command: gp await-port 4200 && gp preview $(gp url 4200)

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addComment: true
    addBadge: false
    addLabel: prebuilt-in-gitpod
